// <auto-generated />
using System;
using BlaBCar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlaBCar.Migrations
{
    [DbContext(typeof(BlaBCarContext))]
    [Migration("20200519213413_ExtendedTrajet")]
    partial class ExtendedTrajet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlaBCar.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("TrajetId")
                        .HasColumnType("int");

                    b.Property<long?>("TrajetId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrajetId1");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BlaBCar.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomBooker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneBooker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BlaBCar.Models.Trajet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AgeChauffeur")
                        .HasColumnType("bigint");

                    b.Property<bool>("Animaux")
                        .HasColumnType("bit");

                    b.Property<bool>("Bagage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("datetime2");

                    b.Property<long>("DureeTrajet")
                        .HasColumnType("bigint");

                    b.Property<bool>("Fumeur")
                        .HasColumnType("bit");

                    b.Property<bool>("Handicape")
                        .HasColumnType("bit");

                    b.Property<string>("LieuArrive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NbrePlaceDispo")
                        .HasColumnType("bigint");

                    b.Property<long>("NbreReservation")
                        .HasColumnType("bigint");

                    b.Property<string>("NomChauffeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelephoneChauffeur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Trajets");
                });

            modelBuilder.Entity("BlaBCar.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlaBCar.Models.Photo", b =>
                {
                    b.HasOne("BlaBCar.Models.Trajet", "Trajet")
                        .WithMany("Photos")
                        .HasForeignKey("TrajetId1");
                });

            modelBuilder.Entity("BlaBCar.Models.Trajet", b =>
                {
                    b.HasOne("BlaBCar.Models.Reservation", null)
                        .WithMany("Trajets")
                        .HasForeignKey("ReservationId");
                });
#pragma warning restore 612, 618
        }
    }
}
